name: flutter_ast
description: A Pure Dart File to Ast Serializer/Deserializer.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_cli_annotations: ^1.0.0
  analyzer:
  path: ^1.7.0
  console: ^3.1.0
  mustache_template: ^1.0.0+1
  _fe_analyzer_shared: ^9.0.0
  recase: ^3.0.0
  test:
  petitparser:

dev_dependencies:
  build_runner: ^1.6.7
  build_cli: ^1.3.9
