name: runner
description: A test runner for the dart programming language.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  test:
  petitparser:  

dev_dependencies:
  build_runner: ^1.6.7
  build_cli: ^1.3.9
